FROM python:3.11-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT=/opt/venv

COPY --from=ghcr.io/astral-sh/uv:0.11.0 /uv /bin/

COPY pyproject.toml .
COPY uv.lock* .
RUN uv sync --no-install-project


COPY . .

CMD ["uv", "run", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]