FROM python:3.11-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT=/opt/venv

COPY --from=ghcr.io/astral-sh/uv:0.11.0 /uv /bin/

COPY pyproject.toml .
COPY uv.lock* .
RUN uv sync --no-install-project

COPY . .

CMD ["uv", "run", "streamlit", "run", "frontend/app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]