services:
  backend:
    image: ghcr.io/kyrbii/project-dvul-backend:latest
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PLOT_SANDBOX_IMAGE=project_dvul_plot_sandbox:latest

  frontend:
    image: ghcr.io/kyrbii/project-dvul-frontend:latest
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend