[project]
name = "project-dvul"
version = "0.1.0"
requires-python = ">=3.11,<3.14"
dependencies = [
    "fastapi",
    "uvicorn",
    "streamlit",
    "langchain",
    "requests",
    "langchain-nvidia-ai-endpoints>=1.2.1",
    "dotenv>=0.9.9",
    "python-multipart>=0.0.26",
    "langchain-community>=0.4.1",
    "matplotlib>=3.10.9",
    "seaborn>=0.13.2",
    "numpy>=2.4.1",
    "pandas>=2.4.0",
    "langchain-openai>=1.2.1",
    "logging>=0.4.9.6",
    "langchain-ollama>=1.1.0",
]

[tool.ruff]
line-length = 88

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]
