import matplotlib.pyplot as plt
import pandas as pd
import os
import uuid
from typing import Dict, Any

def execute_plot_code(code: str, df: pd.DataFrame) -> str:
    """
    Safely executes the plotting code and returns the relative path to the generated SVG.
    """
    # Ensure a plots directory exists
    plots_dir = "static/plots"
    os.makedirs(plots_dir, exist_ok=True)
    
    # Generate a unique filename
    plot_filename = f"plot_{uuid.uuid4().hex[:8]}.svg"
    plot_path = os.path.join(plots_dir, plot_filename)
    
    # Setup the execution environment
    # We provide 'df', 'plt', and 'pd' to the code
    local_vars = {
        "df": df,
        "plt": plt,
        "pd": pd
    }
    
    try:
        # Clear any existing plots to avoid overlap
        plt.close('all')
        
        # Execute the code
        exec(code, {}, local_vars)
        
        # Save the current figure to the path
        # The agent should have used plt.savefig, but we'll do it if it didn't
        if plt.get_fignums():
            plt.savefig(plot_path, format='svg')
            plt.close('all')
            return f"Plot successfully created: {plot_path}"
        else:
            return "Error: No plot was generated by the code."
            
    except Exception as e:
        plt.close('all')
        return f"Error executing plot code: {str(e)}"
